#!/bin/bash
#
# Perform necessary chef-server setup steps after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
	exit 1
}

ln -sf /opt/chef-server/bin/chef-server-ctl /usr/bin || error_exit "Cannot link chef-server-ctl in /usr/bin"

# Ensure all files/directories in $INSTALLER_DIR are owned by root. This
# has been fixed on new installs but upgrades from old installs need to
# be manually fixed.
chown -Rh 0:0 /opt/chef-server

if [ -e /etc/chef-server/chef-server-running.json ]; then
  echo -e "\033[1mYou have upgraded Chef Server!\033[0m"
  echo
  echo "The next step in the upgrade process is to run:"
  echo
  echo -e "\033[1;31msudo chef-server-ctl reconfigure\033[0m"
else
  echo -e "\033[1mThank you for installing Chef Server!\033[0m"
  echo
  echo "The next step in the install process is to run:"
  echo
  echo -e "\033[1msudo chef-server-ctl reconfigure\033[0m"
  # Disable the webui since it is not included in chef-server-core
  # In the future when the webui is separate, we will disable the webui by default and the add-on will have to enable
  grep "chef_server_webui\[[\'\"]enable[\'\"]\]" /etc/chef-server/chef-server.rb >/dev/null 2>&1
  if [ $? == 0 ]; then
    grep "chef_server_webui\[[\'\"]enable[\'\"]\]" /etc/chef-server/chef-server.rb | grep true >/dev/null 2>&1
    if [ $? == 0 ]; then
      echo "Warning: the webui is enabled in /etc/chef-server/chef-server.rb, but this package does not include it"
      exit 1
    fi
  else
    echo "Disabling the webui, which is not included in this package"
    mkdir -p /etc/chef-server
    printf 'chef_server_webui["enable"] = false\n' | tee -a /etc/chef-server/chef-server.rb >/dev/null
  fi
fi

exit 0

